name: Swift Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Swift
        run: |
          curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          ~/.swiftly/bin/swiftly init --quiet-shell-followup
          . "${SWIFTLY_HOME_DIR:-$HOME/.swiftly}/env.sh"
          swiftly install 6.2-snapshot
          hash -r

      - name: Run tests
        run: swift test
